src/flask_app/flaskr/auth.py
import functools

from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from werkzeug.security import check_password_hash
from. import db_user_helper


bp = Blueprint("auth", __name__, url_prefix="/")


@bp.before_app_request
def load_logged_in_user():
    """This function is taken directly from Flask tutorial"""
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = db_user_helper.get_user_by_id(user_id)


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        user = db_user_helper.get_user_by_username(username)

        if user is None:
            error = 'Incorrect username or password.'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect username or password.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('index.index'))

        flash(error)
    return render_template("user/login.html")


@bp.route('/logout')
def logout():
    """This function is taken directly from Flask tutorial"""
    session.clear()
    return redirect(url_for('index.index'))


def login_required(view):
    """This function is taken directly from Flask tutorial"""
    """View decorator that redirects anonymous users to the login page."""

    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            error = "You have to log in"
            flash(error)
            return redirect(url_for("index.index"))

        return view(**kwargs)

    return wrapped_view

src/flask_app/flaskr/covid_blueprint.py
#!/usr/bin/env python3
from flask import (
    Blueprint, render_template, redirect, url_for, flash
    )
import subprocess
import json


bp = Blueprint('covid_blueprint', __name__, url_prefix='/covid')


@bp.route('/', methods=('GET', 'POST'))
def show_stats():
    error = None
    url = 'https://api.covid19api.com/summary'
    response = subprocess.run(
        ['curl', '--location', '--request', 'GET', url], stdout=subprocess.PIPE
    ).stdout

    try:
        response_as_dictionary = json.loads(response)
        global_cases = response_as_dictionary['Global']
    except ValueError:
        error = """You cannot get covid info so often.
                Wait a moment before trying again."""

    if error is None:
        return render_template(
                            "covid_info.html",
                            global_cases=global_cases)

    else:
        flash(error)
        return redirect(url_for('index.index'))

src/flask_app/flaskr/post_blueprint.py
#!/usr/bin/env python3
import datetime
from flask import (
    request, Blueprint, render_template, session, redirect,
    url_for, flash, g
    )
from mysql.connector import Error as mysql_error
from werkzeug import exceptions as request_error
from . import db_post_helper, post
from . import db_comment_helper
from . import auth


bp = Blueprint('post_blueprint', __name__, url_prefix='/post')


@bp.route('/<int:post_id>', methods=('GET', 'POST'))
@auth.login_required
def show_post(post_id):

    logged_user_id = g.user.id

    if request.method == 'POST':
        post_to_delete = int(request.form['delete_id'])
        post_to_edit = int(request.form['edit_id'])
        if post_to_delete != 0:
            session['post_to_delete'] = post_to_delete
            return redirect(url_for('post_blueprint.delete'))
        if post_to_edit != 0:
            session['post_to_edit'] = post_to_edit
            return redirect(url_for('post_blueprint.edit'))

    post = db_post_helper.get_post_by_id(post_id)
    comments = db_comment_helper.get_comments_by_post_id(post_id)

    delete_rights = (logged_user_id == 1)
    edit_rights = (logged_user_id == 1 or logged_user_id == int(post.author_id))

    return render_template(
                            "post/post.html", post=post, comments=comments,
                            edit_rights=edit_rights,
                            delete_rights=delete_rights)


@bp.route('/create', methods=('GET', 'POST'))
@auth.login_required
def create():

    logged_user_id = g.user.id

    if request.method == 'POST':
        error = None

        try:
            title = request.form['title']
            title = title.strip()
        except request_error.BadRequestKeyError:
            error = 'Title is required.'

        if not title:
            error = "Title cannot be empty"

        try:
            category = request.form['category']
        except request_error.BadRequestKeyError:
            error = 'Category is required.'

        try:
            description = request.form['description']
            description = description.replace('\n', '<br>')
            description = description.strip()
        except request_error.BadRequestKeyError:
            error = 'Description is required'

        if not description:
            error = "Description cannot be empty"

        if error is None:
            p = post.Post()
            p.author_id = logged_user_id
            p.title = title
            p.category = category
            p.description = description
            p.created = datetime.datetime.now()
            p.edited = False

            try:
                db_post_helper.insert_post(p)
                message = "Post created"
                flash(message)
                return redirect(url_for('index.index'))
            except mysql_error:
                error = "Oops, a database error occured :("

        flash(error)

    return render_template("post/create_post.html")


@bp.route('/edit', methods=('GET', 'POST'))
@auth.login_required
def edit():

    logged_user_id = g.user.id

    p = db_post_helper.get_post_by_id(session.get('post_to_edit'))
    old_description = p.description
    old_description = old_description.replace('<br>', '\n')
    p.description = old_description

    if logged_user_id != 1 and logged_user_id != p.author_id:
        error = "You do not have rights to edit this post"
        flash(error)
        session.pop('post_to_edit')
        return redirect(url_for('index.index'))

    if request.method == 'POST':
        error = None
        message = None

        try:
            new_description = request.form['description']
            new_description = new_description.replace('\n', '<br>')
            new_description = new_description.strip()
        except request_error.BadRequestKeyError:
            error = 'Description cannot be empty'

        p.description = new_description

        try:
            db_post_helper.update_post(p)
            message = "Post updated!"
        except mysql_error:
            error = "Oops, something went wrong with the database :("

        if error:
            flash(error)
        elif message:
            flash(message)

        return redirect(url_for("index.index"))

    return render_template("post/edit_post.html", post=p)


@bp.route('/delete', methods=('GET', 'POST'))
@auth.login_required
def delete():

    if g.user.role != "admin":
        error = "Only the admin can delete posts"
        flash(error)
        return redirect(url_for('index.index'))

    if request.method == 'POST':
        p = db_post_helper.get_post_by_id(request.form['delete_id'])

        try:
            db_post_helper.delete_post(p)
            session.pop('post_to_delete')
            message = "Post deleted"
            flash(message)
        except mysql_error:
            session.pop('post_to_delete')
            error = "Oops, something went wrong with the database request"
            flash(error)

        return redirect(url_for('index.index'))

    p = db_post_helper.get_post_by_id(session.get('post_to_delete'))

    return render_template("post/delete_post.html", post=p)


def clean_up_session():
    if session.get('post_to_edit'):
        session.pop('post_to_edit')
    elif session.get('post_to_delete'):
        session.pop('post_to_delete')

src/flask_app/flaskr/user_blueprint.py
#!/usr/bin/env python3
from flask import (
    request, Blueprint, render_template, session, redirect,
    url_for, flash, g
    )
from werkzeug.security import check_password_hash, generate_password_hash
from . import db_user_helper, user
from . import db_post_helper
from . import auth
from mysql.connector import Error as mysql_error


bp = Blueprint('user_blueprint', __name__, url_prefix='/')


@bp.route('/users', methods=('GET', 'POST'))
@auth.login_required
def show_users():
    if request.method == 'POST':
        session['viewed_user_id'] = request.form['id']
        return redirect(url_for('user_blueprint.show_user'))

    if g.user.role != "admin":
        error = "Only admin can view all users"
        flash(error)
        return redirect(url_for('index.index'))

    users = db_user_helper.get_users()
    return render_template("user/users.html", users=users)


@bp.route('/user', methods=('GET', 'POST'))
@auth.login_required
def show_user():
    logged_user_id = g.user.id

    if request.method == 'POST':
        user_to_delete = int(request.form['delete_id'])
        user_to_edit = int(request.form['edit_id'])
        if user_to_delete != 0:
            session['user_to_delete'] = user_to_delete
            return redirect(url_for('user_blueprint.delete'))
        if user_to_edit != 0:
            session['user_to_edit'] = user_to_edit
            return redirect(url_for('user_blueprint.edit'))

    if session.get('viewed_user_id'):
        viewed_user_id = int(session['viewed_user_id'])

        session.pop('viewed_user_id')
    else:
        viewed_user_id = logged_user_id

    user = db_user_helper.get_user_by_id(viewed_user_id)
    posts = db_post_helper.get_posts_by_user_id(viewed_user_id)

    delete_rights = (g.user.role == "admin")
    edit_rights = (g.user.role == "admin" or int(logged_user_id) == int(viewed_user_id))

    return render_template(
                            "user/user.html", user=user, posts=posts,
                            edit_rights=edit_rights,
                            delete_rights=delete_rights)


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        password2 = request.form['password2']
        email = request.form['email']
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif password != password2:
            error = "Passwords must match"
        elif not email:
            error = 'Email is required'
        elif db_user_helper.get_user_by_username(username) is not None:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            u = user.User()
            u.username = username
            u.password = (generate_password_hash(password))
            u.email = email

            try:
                db_user_helper.insert_user(u)
                return redirect(url_for('auth.login'))
            except mysql_error:
                error = "A user with this email address is already registered."

        flash(error)

    return render_template("user/register.html")


@bp.route('/edituser', methods=('GET', 'POST'))
@auth.login_required
def edit():

    logged_user_id = g.user.id
    edit_user_id = int(session.get('user_to_edit'))

    if g.user.role != "admin" and logged_user_id != edit_user_id:
        error = "You do not have rights to edit this user"
        flash(error)
        session.pop('user_to_edit')
        return redirect(url_for('index.index'))

    u = db_user_helper.get_user_by_id(edit_user_id)

    if request.method == 'POST':
        old_password = request.form['old_password']
        new_password = request.form['new_password']
        new_password2 = request.form['new_password2']
        email = request.form['email']
        error = None
        message = None

        if not check_password_hash(u.password, old_password):
            error = 'Incorrect password.'
            flash(error)
            return redirect(url_for("user_blueprint.edit", user=u))

        if new_password:
            if new_password == old_password:
                error = 'New password has to be new'
            elif new_password != new_password2:
                error = 'Passwords must match'
            else:
                u.password = (generate_password_hash(new_password))
                message = "User updated!"
                try:
                    db_user_helper.update_user_password(u)
                except mysql_error:
                    error = "Oops, something went wrong with the database"

        if email:
            u.email = email
            try:
                db_user_helper.update_user_email(u)
                message = "User updated!"
            except mysql_error:
                error = "A user with this email already exists in our database"

        if error:
            flash(error)
        elif message:
            flash(message)

        return redirect(url_for("index.index"))

    return render_template("user/edit_user.html", user=u)


@bp.route('/deleteuser', methods=('GET', 'POST'))
@auth.login_required
def delete():

    if not g.user.role == "admin":
        error = "Only the admin can delete users"
        clean_up_session()
        flash(error)
        return redirect(url_for('index.index'))

    if request.method == 'POST':
        uid = request.form['delete_id']
        u = db_user_helper.get_user_by_id(uid)

        try:
            db_user_helper.delete_user(u)
            message = "User deleted"
            flash(message)
        except mysql_error:
            error = "Oops, something went wrong with the database request"
            flash(error)

        clean_up_session()
        return redirect(url_for('index.index'))

    delete_user_id = session.get('user_to_delete')
    u = db_user_helper.get_user_by_id(delete_user_id)

    return render_template("user/delete_user.html", user=u)


def clean_up_session():
    if session.get('user_to_edit'):
        session.pop('user_to_edit')
    elif session.get('user_to_delete'):
        session.pop('user_to_delete')

src/flask_app/flaskr/templates/base.html
<!doctype html>
<head>
  <title>Coronaboard</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script type=text/javascript src="{{ url_for('static', filename='scripts/script.js') }}"></script>
</head>
<nav class="navbar">
  <h1><a href="{{ url_for('index.index') }}"><img id="logo" src="{{ url_for('static', filename='images/corona.png') }}">Coronaboard</a></h1>
  {% if g.user %}
  <a href="{{ url_for('post_blueprint.create') }}"><button class="btn-success">Create new post</button></a>
  {% endif %}
  <ul>
    {% if g.user %}
      <li>You're logged in as <a href="{{ url_for('user_blueprint.show_user') }}">{{ g.user['username'] }}</a>
      {% if g.user['id']==1 %}
      <li><a href="{{ url_for('user_blueprint.show_users') }}">See all Coronaboard users</a>
      {% endif %}
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('user_blueprint.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>
<footer>
&copy; Wiktor Sierpiński
</footer>

src/flask_app/flaskr/templates/covid_info.html
{% extends 'base.html' %}

{% block header %}
  {% block title %}<h1>Global stats</h1>{% endblock %}
{% endblock %}

{% block content %}
<div class="container">
  <table class="table normal-text">
    <tr>
      <td>New confirmed cases globally</td>
      <td>{{ global_cases.NewConfirmed }}</td>
    </tr>
    <tr>
      <td>Total confirmed cases globally</td>
      <td>{{ global_cases.TotalConfirmed }}</td>
    </tr>
    <tr>
      <td>New deaths globally</td>
      <td>{{ global_cases.NewDeaths }}</td>
    </tr>
    <tr>
      <td>Total deaths globally</td>
      <td>{{ global_cases.TotalDeaths }}</td>
    </tr>
    <tr>
      <td>New recovered globally</td>
      <td>{{ global_cases.NewRecovered }}</td>
    </tr>
    <tr>
      <td>Total recovered globally</td>
      <td>{{ global_cases.TotalRecovered }}</td>
    </tr>
  </table>
</div>
{% endblock %}

src/flask_app/flaskr/templates/index.html
{% extends 'base.html' %}

{% block header %}
  {% block title %}{% endblock %}
{% endblock %}

{% block content %}
<div class="container">
  <form action="/posts" method="post">
    <label for="category">Filter posts</label>
    <select id="category" name="category">
      <option selected disabled hidden style='display: none' value=''></option>
      <option value="groceries">Posts about groceries</option>
      <option value="dogs">Posts about dog walking</option>
    </select>
    <input class="btn-success" type="submit" value="Select">
  </form>
  <div class="row">
    {% for post in posts %}
      <div class="col-sm-4 single-post">
        <h3>
          <a href='/post/{{ post['id'] }}'>{{ post['title'] }}</a>
        </h3>
        {% if post['category']=='dogs' %}
            <img class="category-picture" src="{{ url_for('static', filename='images/paw.png') }}"> Dog walking
        {% elif post['category']=='groceries' %}
            <img class="category-picture" src="{{ url_for('static', filename='images/groceries.png') }}"> Groceries
        {% endif %}
        <div class="paper">
          <h3>
            {{ post['title'] }}
            <img id="pin" src="{{ url_for('static', filename='images/drawing-pin.png') }}">
          </h3>
          {{ post['description'] | safe }}
        </div>
          <div class="row">
            <i><small>created {{ post['created'] }} by</small></i>&nbsp;
            <form action="/users" method="post">
              <input type="hidden" id="id" name="id" value="{{ post['author_id'] }}">
              <button class="link" type="submit" value="Submit"">{{ post['author']['username'] }}</button>
            </form>
          </div>
          {% if post['edited'] %}
            edited
          {% endif %}

      </div>
    {% endfor %}
  </div>
  {{ pagination.links }}
  <a href="{{ url_for('covid_blueprint.show_stats') }}">See current covid info</a>
</div>
{% endblock %}